site_name: PPS - Unidad 0 - Tarea RA5 - Óscar
theme:
  name: mkdocs

nav:
  - Inicio: index.md
  - 1. Creación del Repositorio: git.md
  - 2. GitHub Actions (Workflow): gitActions.md
  - 3. GitHub Pages (Publicación): gitPages.md
  - 4. Docker & NGINX (Despliegue local): docker.md
  - Conclusiones: conclusiones.md

