site_name: PPS-Unidad0-TareaRA5 - Óscar
theme:
  name: mkdocs

nav:
  - Inicio: index.md
  - 1. Creación del Repositorio: git.md
  - 2. GitHub Actions: gitActions.md
  - 3. GitHub Pages: gitPages.md
  - 4. Docker & NGINX: docker.md
  - 5. Conclusiones: conclusiones.md
